services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    logging:
      driver: none

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - 9092:9092
    depends_on:
      - zookeeper

  producer:
    build: 
      context: ./kafka-producer
      dockerfile: ./Dockerfile

  consumer:
    build: 
      context: ./kafka-consumer
      dockerfile: ./Dockerfile
    depends_on:
      - producer
