version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    logging:  
      driver: none

  kafka:
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    hostname: 'kafka-internal.io'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-internal.io
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    logging:  
      driver: none

  producer:
    ports:
      - 3000:3000
    build: 
      context: ./kafka-producer
      dockerfile: ./Dockerfile
    depends_on:
      - kafka

  consumer:
    build: 
      context: ./kafka-consumer
      dockerfile: ./Dockerfile
    depends_on:
      - producer


